format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$python\
$golang\
$status\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[fill]
symbol = " "

[directory]
home_symbol = "~"
style = "cyan bold"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = ".../"

[docker_context]
symbol = "(docker) "

[git_branch]
format = "[git:$branch]($style)"
style = "green"

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​=$count "
untracked = "​?$count "
modified = "​!$count "
staged = "​+$count "
renamed = "»$count ​"
deleted = "​✘$count "
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
symbol = "(go) "
format = "[$symbol$version](cyan bold) "

[hg_branch]
symbol = "(hg) "

[kubernetes]
disabled = false
symbol = "(k8s)"
format = "[$symbol$context](cyan bold) "

[python]
format = "([(py) $virtualenv]($style)) "

[rust]
symbol = "(rust) "

[status]
disabled = false

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false

