#!/bin/bash
if [[ -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]]; then
    # Arch Linux
    exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
elif [[ -f /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ]]; then
    # Ubuntu
    exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
fi