#!/bin/bash
set -euo pipefail
# Output green message prefixed with [+]
_info() { echo -e "\e[92m[+] ${1:-}\e[0m"; }

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$(dirname "${DIR}")" && pwd)
GITHUB="https://github.com"

# Set default shells
if command -v zsh >/dev/null; then
	_info "Changing default shells to zsh for '$USER' and 'root'"
	sudo chsh -s /bin/zsh "$USER"
	sudo chsh -s /bin/zsh root
fi

mkdir -p "${HOME}/.config"

# zsh config
_info "Linking zsh configs"
ln -sf "${REPO}/zsh/.zshrc" "${HOME}/.zshrc"
[[ ! -L ${HOME}/.zsh_config ]] && ln -sf "${REPO}/zsh/.zsh_config" "${HOME}/.zsh_config"

if [[ ! -d ${HOME}/.zsh_config/zsh-autosuggestions ]]; then
	_info "Cloning zsh-autosuggestions from Github"
	git clone "${GITHUB}/zsh-users/zsh-autosuggestions" "$HOME/.zsh_config/zsh-autosuggestions"
fi

if [[ ! -d ${HOME}/.zsh_config/zsh-syntax-highlighting ]]; then
	_info "Cloning zsh-syntax-highlighting from Github"
	git clone "${GITHUB}/zsh-users/zsh-syntax-highlighting" "$HOME/.zsh_config/zsh-syntax-highlighting"
fi

# starship config
_info "Linking starship configs"
ln -sf "${REPO}/starship/starship.toml" "${HOME}/.config/starship.toml"
ln -sf "${REPO}/starship/starship-plain.toml" "${HOME}/.config/starship-plain.toml"

# htop config
_info "Linking htop config"
mkdir -p "${HOME}/.config/htop"
ln -sf "${REPO}/htop/htoprc" "${HOME}/.config/htop/htoprc"

# xdg-config
_info "Linking xdg-user-dirs config"
ln -sf "${REPO}/xdg-user-dirs/user-dirs.dirs" "${HOME}/.config/user-dirs.dirs"

# git config
_info "Linking git configs"
ln -sf "${REPO}/git/.gitconfig" "${HOME}/.gitconfig"
ln -sf "${REPO}/git/.gitignore" "${HOME}/.gitignore"

# tmux config
_info "Linking bat config"
[[ ! -L "${HOME}/.config/bat" ]] && ln -sf "${REPO}/bat" "${HOME}/.config/bat"

# tmux config
_info "Linking tmux config"
ln -sf "${REPO}/tmux/.tmux.conf" "${HOME}/.tmux.conf"
[[ ! -L "${HOME}/.tmux" ]] && ln -sf "${REPO}/tmux/.tmux" "${HOME}/.tmux"

# vim config
_info "Linking vim configs"
mkdir -p "${HOME}/.vim/bundle"
ln -sf "${REPO}/vim/.vimrc" "${HOME}/.vimrc"
ln -sf "${REPO}/vim/setup.vim" "${HOME}/.vim/setup.vim"

if [[ ! -d "${HOME}/.vim/bundle/Vundle.vim" ]]; then
	_info "Cloning Vundle from Github"
	git clone "${GITHUB}/VundleVim/Vundle.vim.git" "${HOME}/.vim/bundle/Vundle.vim"
fi

_info "Running vim setup script"
vim -s "${HOME}/.vim/setup.vim"

# Root user stuff
_info "Configuring zsh for root user"
sudo cp "${REPO}/zsh/root.zshrc" "/root/.zshrc"
sudo mkdir -p "/root/.config"
sudo cp "${REPO}/starship/starship-plain.toml" "/root/.config/starship.toml"

# misc config
mkdir -p "${HOME}/.ssh"
